version = 1

[[annotations]]
path = [
 "assets/**",
 "config/**",
 "lib/**",
 "mix.lock",
 "rel/**",
 "rootfs_overlay/**",
 "REUSE.toml",
 "test/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
